code --install-extension akamud.vscode-javascript-snippet-pack
code --install-extension burkeholland.simple-react-snippets
code --install-extension castwide.solargraph
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension daohong-emilio.yash
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension esbenp.prettier-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension gruntfuggly.todo-tree
code --install-extension henrytsz.nvim
code --install-extension james-yu.latex-workshop
code --install-extension jasonnutter.search-node-modules
code --install-extension kohlbachjan.the-best-theme
code --install-extension leizongmin.node-module-intellisense
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpp-devtools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.js-debug-nightly
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension pkief.material-icon-theme
code --install-extension redhat.java
code --install-extension suriyagokul.node-js-express-snippets
code --install-extension tomoki1207.pdf
code --install-extension vscjava.migrate-java-to-azure
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-java-upgrade
code --install-extension vscjava.vscode-maven
code --install-extension vscodevim.vim
code --install-extension wakatime.vscode-wakatime
code --install-extension wallabyjs.wallaby-vscode
code --install-extension xabikos.javascriptsnippets
code --install-extension yandeu.five-server
